/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabomb;

import java.util.Random;

/**
 *
 * @author Javier Vargas
 */
public class bomba extends javax.swing.JFrame {
    int lock = 0;
    int exit = 0;
    
   public static boolean getRandomBoolean() {
    return Math.random() < 0.5;
   }
    /**
     * Creates new form bomba
     */
    public bomba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bomb.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 130, 160, 210);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bomb.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setPreferredSize(new java.awt.Dimension(680, 460));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 130, 160, 210);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bomb.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 130, 160, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tienes 1 Oportunidad!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 380, 200, 50);

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 480, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (lock == 0){
        Random rand = new Random();
        boolean value = rand.nextBoolean();
        if (value == true) {
            jLabel1.setText("Puedes Continuar!");
            jButton4.setText("Continuar");
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/defuse.png")));
        }
        if (value == false) {
            jLabel1.setText("Haz Perdido!");
            exit = 1;
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exp.png")));
        }
    lock = 1;
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (lock == 0){
        Random rand = new Random();
        boolean value = rand.nextBoolean();
        if (value == true) {
            jLabel1.setText("Puedes Continuar!");
            jButton4.setText("Continuar");
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/defuse.png")));
        }
        if (value == false) {
            jLabel1.setText("Haz Perdido!");
            exit = 1;
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exp.png")));
        }
    lock = 1;
    }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (lock == 0){
        Random rand = new Random();
        boolean value = rand.nextBoolean();
        if (value == true) {
            jLabel1.setText("Puedes Continuar!");
            jButton4.setText("Continuar");
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/defuse.png")));
        }
        if (value == false) {
            jLabel1.setText("Haz Perdido!");
            exit = 1;
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exp.png")));
        }
    lock = 1;
    }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if (exit == 1){
        ventana obj = new ventana();
        obj.setVisible(true);
        dispose();
    }
    else {
        juego obj = new juego();
        obj.setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bomba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
