/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zzz;

import java.util.ArrayList;

/**
 *
 * @author patricio mercado y Javier Vargas
 */
public class FramGame extends javax.swing.JFrame {

    /**
     * Creates new form FramGame
     */
    private Juego partida;
    
    /**
     * constructor de la clase principal del juego, se le asigna un arraylist que se utilizara con los metodos quitarJLabels, para
     * quitar los labels de los jugadores y scores que no se utilizaran durante la operacion
     * @param p ArrayList con el nombre y puntaje de los Jugadores, de tipo Players
     */
    public FramGame(ArrayList<Player> p) {
        initComponents();
        
        controlFrame control = new controlFrame(p.size());
        control.quitarJLabel(jug1, jug2, jug3, jug4, jug5, jug6, jug7);
        control.quitarJLabel(score1, score2, score3, score4, score5, score6, score7);
        control.mostrarJugadores(p, jug1, jug2, jug3, jug4, jug5, jug6, jug7);
        control.mostrarPuntaje(p, score1, score2, score3, score4, score5, score6, score7);
        partida = new Juego(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jug1 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        jug2 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jug3 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        jug4 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        jug5 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        jug6 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        jug7 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregun = new javax.swing.JTextArea();
        siguiente = new javax.swing.JButton();
        botonDado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jug1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jug1.setText("jLabel1");
        getContentPane().add(jug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, -1, -1));

        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setText("jLabel2");
        getContentPane().add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jug2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug2.setText("jLabel3");
        getContentPane().add(jug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, -1, -1));

        score2.setText("jLabel4");
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jug3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug3.setText("jLabel5");
        getContentPane().add(jug3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 11, -1, -1));

        score3.setText("jLabel6");
        getContentPane().add(score3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jug4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug4.setText("jLabel7");
        getContentPane().add(jug4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 11, -1, -1));

        score4.setText("jLabel8");
        getContentPane().add(score4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jug5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug5.setText("jLabel9");
        getContentPane().add(jug5, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 11, -1, -1));

        score5.setText("jLabel0");
        getContentPane().add(score5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jug6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug6.setText("jLabel11");
        getContentPane().add(jug6, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 11, -1, -1));

        score6.setText("jLabel12");
        getContentPane().add(score6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jug7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jug7.setText("jLabel13");
        getContentPane().add(jug7, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 11, -1, -1));

        score7.setText("jLabel14");
        getContentPane().add(score7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        pregun.setEditable(false);
        pregun.setColumns(20);
        pregun.setRows(5);
        jScrollPane1.setViewportView(pregun);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 68, 382, 170));

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 252, -1, -1));

        botonDado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz/dados-04.gif"))); // NOI18N
        botonDado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDadoActionPerformed(evt);
            }
        });
        getContentPane().add(botonDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 109, -1, 81));
        botonDado.getAccessibleContext().setAccessibleName("cdd");
        botonDado.getAccessibleContext().setAccessibleDescription("111");

        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 530, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz/aaa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton siguiente, junto a los metodos checkea si ya se ha lanzado eldado y si alguno de los jugadores ya gano eljuego.
     * en caso de que gane el juego, se muestra la pantalla final.
     * @param evt ActionEvent para el boton Siguiente
     */
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        
        boolean estado =partida.chequear(botonDado,pregun);
        setVisible(estado);
        partida.actualizarLabels(score1,score2,score3,score4,score5,score6,score7);
        if (estado== false) {
            FramGanador fg = new FramGanador(partida.getGanador());
            fg.setVisible(true);
        } 
        
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * Botonque activa el evento para simular el lanzamiento de un dado
     * @param evt Evento que captura la accion realizada con el botondado.
     */
    private void botonDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDadoActionPerformed
        partida.lanzarDado(botonDado,pregun);
        
    }//GEN-LAST:event_botonDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jug1;
    private javax.swing.JLabel jug2;
    private javax.swing.JLabel jug3;
    private javax.swing.JLabel jug4;
    private javax.swing.JLabel jug5;
    private javax.swing.JLabel jug6;
    private javax.swing.JLabel jug7;
    private javax.swing.JTextArea pregun;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
