/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zzz;

/**
 *
 * @author patricio mercado y Javier Vargas
 */
public class FramIngr extends javax.swing.JFrame {

    /**
     * Creates new form FramIngr
     */
    private Gamers g = new Gamers();
    
    /**
     * Constructor de l clase sin parametros,inicializa los componentes de la ventana y realiza
     * una limpieza de las labels que no se utilizaran
     */
    public FramIngr() {
        initComponents();
        g.numJugadores();
        controlFrame control = new controlFrame(g.getNumJugadores());
        control.correctorTextField(jug1, jug2, jug3, jug4, jug5, jug6, jug7);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jug1 = new javax.swing.JTextField();
        jug2 = new javax.swing.JTextField();
        jug3 = new javax.swing.JTextField();
        jug4 = new javax.swing.JTextField();
        jug5 = new javax.swing.JTextField();
        jug6 = new javax.swing.JTextField();
        jug7 = new javax.swing.JTextField();
        listo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jug1.setText("Jugador 1");
        jug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug1ActionPerformed(evt);
            }
        });
        getContentPane().add(jug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 83, 89, -1));

        jug2.setText("Jugador 2");
        jug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug2ActionPerformed(evt);
            }
        });
        getContentPane().add(jug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 83, 89, -1));

        jug3.setText("Jugador 3");
        jug3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug3ActionPerformed(evt);
            }
        });
        getContentPane().add(jug3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 121, 89, -1));

        jug4.setText("Jugador 4");
        getContentPane().add(jug4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 121, 89, -1));

        jug5.setText("Jugador 5");
        getContentPane().add(jug5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 159, 89, -1));

        jug6.setText("Jugador 6");
        getContentPane().add(jug6, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 159, 89, -1));

        jug7.setText("Jugador 7");
        jug7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug7ActionPerformed(evt);
            }
        });
        getContentPane().add(jug7, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 197, 89, -1));

        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });
        getContentPane().add(listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 258, -1, -1));

        jLabel1.setFont(new java.awt.Font("Game of Thrones", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese   nombres   de   los   jugadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz/bar-780x300.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejo del evento al presionar el boton listo, el cual guarda los datos introducidos en los textarea
     * con los nombres de los jugadores, posteriormente los une en un array de String para crear la colleccion
     * de Jugadores(Players)
     * @param evt 
     */
    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        // TODO add your handling code here:
        
        String[] jugadores = {jug1.getText(),jug2.getText(),jug3.getText(),jug4.getText(),jug5.getText(),jug6.getText(),jug7.getText()};
        for (int i = 0; i < g.getNumJugadores(); i++) {
            g.addGamers(jugadores[i]);
        }
        setVisible(false);
        FramGame fg = new FramGame(g.getGamers());
        fg.setVisible(true);
        
    }//GEN-LAST:event_listoActionPerformed

    private void jug3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug3ActionPerformed

    private void jug7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug7ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jug7ActionPerformed

    private void jug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug2ActionPerformed

    private void jug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jug1;
    private javax.swing.JTextField jug2;
    private javax.swing.JTextField jug3;
    private javax.swing.JTextField jug4;
    private javax.swing.JTextField jug5;
    private javax.swing.JTextField jug6;
    private javax.swing.JTextField jug7;
    private javax.swing.JButton listo;
    // End of variables declaration//GEN-END:variables
}
