/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zzz;

import java.util.ArrayList;

/**
 *
 * @author patricio mercado y Javier Vargas
 */
public class FramGame extends javax.swing.JFrame {

    /**
     * Creates new form FramGame
     */
    private Juego partida;
    
    /**
     * constructor de la clase principal del juego, se le asigna un arraylist que se utilizara con los metodos quitarJLabels, para
     * quitar los labels de los jugadores y scores que no se utilizaran durante la operacion
     * @param p ArrayList con el nombre y puntaje de los Jugadores, de tipo Players
     */
    public FramGame(ArrayList<Player> p) {
        initComponents();
        
        controlFrame control = new controlFrame(p.size());
        control.quitarJLabel(jug1, jug2, jug3, jug4, jug5, jug6, jug7);
        control.quitarJLabel(score1, score2, score3, score4, score5, score6, score7);
        control.mostrarJugadores(p, jug1, jug2, jug3, jug4, jug5, jug6, jug7);
        control.mostrarPuntaje(p, score1, score2, score3, score4, score5, score6, score7);
        partida = new Juego(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jug1 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        jug2 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jug3 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        jug4 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        jug5 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        jug6 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        jug7 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregun = new javax.swing.JTextArea();
        siguiente = new javax.swing.JButton();
        botonDado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jug1.setText("jLabel1");

        score1.setText("jLabel2");

        jug2.setText("jLabel3");

        score2.setText("jLabel4");

        jug3.setText("jLabel5");

        score3.setText("jLabel6");

        jug4.setText("jLabel7");

        score4.setText("jLabel8");

        jug5.setText("jLabel9");

        score5.setText("jLabel0");

        jug6.setText("jLabel11");

        score6.setText("jLabel12");

        jug7.setText("jLabel13");

        score7.setText("jLabel14");

        pregun.setEditable(false);
        pregun.setColumns(20);
        pregun.setRows(5);
        jScrollPane1.setViewportView(pregun);

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        botonDado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz/dados-04.gif"))); // NOI18N
        botonDado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(siguiente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jScrollPane1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botonDado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jug1)
                                .addComponent(score1))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jug2)
                                .addComponent(score2))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jug3)
                                .addComponent(score3))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jug4)
                                .addComponent(score4))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(score5)
                                .addComponent(jug5))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jug6)
                                .addComponent(score6))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(score7)
                                .addComponent(jug7)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jug1)
                            .addComponent(jug2)
                            .addComponent(jug3)
                            .addComponent(jug4)
                            .addComponent(jug5)
                            .addComponent(jug6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(score1)
                                .addComponent(score2)
                                .addComponent(score3)
                                .addComponent(score4)
                                .addComponent(score5))
                            .addComponent(score6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jug7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(botonDado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(siguiente)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        botonDado.getAccessibleContext().setAccessibleName("cdd");
        botonDado.getAccessibleContext().setAccessibleDescription("111");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton siguiente, junto a los metodos checkea si ya se ha lanzado eldado y si alguno de los jugadores ya gano eljuego.
     * en caso de que gane el juego, se muestra la pantalla final.
     * @param evt ActionEvent para el boton Siguiente
     */
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        boolean estado =partida.chequear(botonDado,pregun);
        setVisible(estado);
        partida.actualizarLabels(score1,score2,score3,score4,score5,score6,score7);
        if (estado== false) {
            FramGanador fg = new FramGanador(partida.getGanador());
            fg.setVisible(true);
        } 
        
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * Botonque activa el evento para simular el lanzamiento de un dado
     * @param evt Evento que captura la accion realizada con el botondado.
     */
    private void botonDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDadoActionPerformed
        partida.lanzarDado(botonDado,pregun);
        
    }//GEN-LAST:event_botonDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jug1;
    private javax.swing.JLabel jug2;
    private javax.swing.JLabel jug3;
    private javax.swing.JLabel jug4;
    private javax.swing.JLabel jug5;
    private javax.swing.JLabel jug6;
    private javax.swing.JLabel jug7;
    private javax.swing.JTextArea pregun;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
