/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GoD;

/**
 *
 * @author patricio mercado y Javier Vargas
 */
public class FramIngr extends javax.swing.JFrame {

    /**
     * Creates new form FramIngr
     */
    private Gamers g = new Gamers();
    
    /**
     * Constructor de l clase sin parametros,inicializa los componentes de la ventana y realiza
     * una limpieza de las labels que no se utilizaran
     */
    public FramIngr() {
        initComponents();
        g.numJugadores();
        controlFrame control = new controlFrame(g.getNumJugadores());
        control.correctorTextField(jug1, jug2, jug3, jug4, jug5, jug6, jug7);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jug1 = new javax.swing.JTextField();
        jug2 = new javax.swing.JTextField();
        jug3 = new javax.swing.JTextField();
        jug4 = new javax.swing.JTextField();
        jug5 = new javax.swing.JTextField();
        jug6 = new javax.swing.JTextField();
        jug7 = new javax.swing.JTextField();
        listo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jug1.setText("Jugador 1");
        jug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug1ActionPerformed(evt);
            }
        });

        jug2.setText("Jugador 2");
        jug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug2ActionPerformed(evt);
            }
        });

        jug3.setText("Jugador 3");
        jug3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug3ActionPerformed(evt);
            }
        });

        jug4.setText("Jugador 4");

        jug5.setText("Jugador 5");

        jug6.setText("Jugador 6");

        jug7.setText("Jugador 7");
        jug7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jug7ActionPerformed(evt);
            }
        });

        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese nombres de los jugadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jug7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jug5)
                    .addComponent(jug3)
                    .addComponent(jug1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jug6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jug4)
                        .addComponent(jug2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(listo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jug6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jug5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jug7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(listo)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejo del evento al presionar el boton listo, el cual guarda los datos introducidos en los textarea
     * con los nombres de los jugadores, posteriormente los une en un array de String para crear la colleccion
     * de Jugadores(Players)
     * @param evt 
     */
    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        // TODO add your handling code here:
        
        String[] jugadores = {jug1.getText(),jug2.getText(),jug3.getText(),jug4.getText(),jug5.getText(),jug6.getText(),jug7.getText()};
        for (int i = 0; i < g.getNumJugadores(); i++) {
            g.addGamers(jugadores[i]);
        }
        setVisible(false);
        FramGame fg = new FramGame(g.getGamers());
        fg.setVisible(true);
        
    }//GEN-LAST:event_listoActionPerformed

    private void jug3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug3ActionPerformed

    private void jug7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug7ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jug7ActionPerformed

    private void jug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug2ActionPerformed

    private void jug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jug1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jug1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jug1;
    private javax.swing.JTextField jug2;
    private javax.swing.JTextField jug3;
    private javax.swing.JTextField jug4;
    private javax.swing.JTextField jug5;
    private javax.swing.JTextField jug6;
    private javax.swing.JTextField jug7;
    private javax.swing.JButton listo;
    // End of variables declaration//GEN-END:variables
}
